tienPh commit: contract Marketplace.sol code auction
xieuxaythit/BDA.Marketplace pull request #1
Opened 2021-07-28 11:05 UTC by Niet-Pham

-create: Marketplace.sol. code functions auction

2021-07-30 12:08 UTC, xieuxaythit requested changes

2021-07-30 12:08 UTC, xieuxaythit commented on contracts/NginNFT.sol
> +        _tokenBaseUri = _uri;
@Niet-Pham chỗ này ko cần hàm _setBaseURI()?

2021-07-30 12:08 UTC, xieuxaythit commented on contracts/NginNFT.sol
> +    mapping(uint => string) tokenHashById;
``` Suggestion
    mapping(uint => bytes32) tokenHashById;
```
Chuyển về bytes32 sẽ tiết kiệm bộ nhớ hơn

2021-08-02 03:07 UTC, Niet-Pham commented on contracts/NginNFT.sol
> +        _tokenBaseUri = _uri;
hình như chỗ này trong code của em nó cũng k để setBaseURi a ạ.

2021-08-09 04:06 UTC, xieuxaythit approved these changes

2021-08-09 04:06 UTC, xieuxaythit approved these changes

2021-08-09 04:09 UTC, merged